server:
  port: 4321

spring:
  thymeleaf:
    cache: false


# test ConditionalOnProperty annotation
parent-name:
  name:




#  son-name: true
#parent-name:
#  son-name:
#parent-name:
#  son-name: false
#parent-name:
#  son-name: null
#parent-name:
#  son-name: 123